name: CI
on:
  push:
    branches: 
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - run: sbt test
      - run: sbt exemples/compile
